name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Xvfb for GUI support
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Start virtual display (Xvfb)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "Xvfb started on :99"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Maven tests with GUI
        env:
          DISPLAY: :99
        run: mvn -B clean test