name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Xvfb and GUI tools
        run: sudo apt-get update && sudo apt-get install -y xvfb x11-utils

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Verify Xvfb running
        run: xdpyinfo -display :99 || (echo "Xvfb not running" && exit 1)

      - name: Run tests with GUI support
        env:
          DISPLAY: :99
          _JAVA_OPTIONS: "-Djava.awt.headless=false"
        run: mvn -B clean test

      - name: Upload JUnit test results
        if: always()  # ensure it runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/
